### ISSUE TITLE
The /raid command isn't recording a segment and raid appropriately

### ISSUE THREAD

**Issue by MichaelJolley** [MichaelJolley/io#104]

**Comment by parithon** [comment]
I believe we came to a consensus that the issue is that the /raid command is not "echoed" to the IIRC channel where the bot is listening... we also generated a new command "!raid" to solve this problem.

I went ahead and verified our assumption. That said, Twitch' IIRC does send a **hosting** message that you're now hosting the channel you raided. Perhaps we can use that to automatically generate the raid segment.

```TypeScript
this.tmi.on('hosting', (channel: string, target: string, viewers: number): void => {
  // ... do something awesome ...
});
```
