### ISSUE TITLE
Change RAID sound to "Rock you like a Hurricane"

### ISSUE THREAD

**Issue by ToeFrog** [MichaelJolley/io#144]
When someone raids the stream have "Rock You Like a Hurricane" play instead of the Good, Bad, and Ugly. (Mentioned in stream on 10/10/2019)

**Comment by ToeFrog** [comment]
Working on it.

**Comment by MichaelJolley** [comment]
This is great @ToeFrog!  One change though, we don't want to play it for every raid. Just when the `raider.user.login === 'cldubya'`  since Corey's nickname is Hurricane.

You're rocking this one!  

![bitmoji](https://render.bitstrips.com/v2/cpanel/f5f350c4-9252-4cb3-a6f0-d3990389fc90-b24761f5-99bf-4885-9465-63838b10c2c3-v1.png?transparent=1&palette=1&width=246)

**Comment by ToeFrog** [comment]
@MichaelJolley Got it. I'll tweak it.

**Comment by ToeFrog** [comment]
@MichaelJolley Updated.
