### ISSUE TITLE
Add volume mapping for node modules and source code for node services

### ISSUE THREAD

**Issue by mtheoryx** [MichaelJolley/io#47]
Suggest adding source code volume mounts to aid in faster development iteration with docker-compose.

Currently, making a change in the code will not be reflected in the running container. Even on a container restart.

The issue is that there are `COPY` commands in the Dockerfile. This is the BUILD phase.

But the runtime phase simply runs the container from the already-built image.

Using the `volume` directive in your docker compose can aid in rapid iteration during development to avoid the BUILD step because the volume over-write is a RUNTIME directive.

[You can see an example repo here](https://github.com/mtheoryx/roberttables-livestream/blob/master/docker-compose.yml)

The important bits are this:

```yaml
    volumes:
      - ./public-site:/usr/app
      - /usr/app/node_modules
```

**Comment by MichaelJolley** [comment]
I'm not familiar with this at all.  I like the sound of it and can't wait for you to teach me/us.

**Comment by MichaelJolley** [comment]
Not where this belongs, but oh well...

@all-contributors please add @parithon for code and infra

**Comment by mtheoryx** [comment]
I'm going to include several changes with this, as well as resource links for why certain things are changing, and I'm happy to discord call and go over it.

I'm also making certain assumptions about your development style, and you most likely are going to want to pull this down and test it out.

My proposed changes:

- [ ] Change the Dockerfile command to directly execute node against the dist file, instead of proxying to npm (there is a reason for this)
- [ ] Add an "init" property to the docker-compose file to wrap the command in a thin init layer to handle signals even better than item above (there is a reason for this)
- [ ] Use a non-root user for all containers (there is a reason for this)
- [ ] Add volume mounts (this is the original heart of the issue, but other things are required to take advantage of this, mentioned in below items)
- [ ] Add typescript watching, and node process re-starting, as additional npm script commands, and use the docker-compose file to execute this in dev, overriding the default build and start of the container command

I'll be monitoring this issue as I develop and am happy to discuss any concerns with the above-proposed changes.

**Comment by mtheoryx** [comment]
Also, we should probably specify actual container names in the docker-compose (like we specify image names) for tracking down and interrogating particular containers. 

I'll tack that on as well, no sweat.

**Comment by MichaelJolley** [comment]
Was this handled in the recent @parithon PR to allow debugging?

**Comment by mtheoryx** [comment]
@MichaelJolley It was partially, I'll update this issue to reflect that looks like already complete!

**Comment by parithon** [comment]
@mtheoryx and @MichaelJolley, to better document why I added the other `*.dockerfile`'s located in the `services` folder:

I noticed when I built the images for use with the docker-compose containers, the 'node_modules' folder does not include the `devDependencies` most likely because the `Dockerfile` installs with the `--only=Production` flag during the second phase of their build process.

I decided to simply create _development_ Dockerfile's and placed them in the `services` folder emitting the second phase and mounting the entire service' folder in docker-compose so we can develop based on changes from the host.

My intent wasn't to remove or replace the _production_ Dockerfile's located in each of the services root folders, nor any work that @mtheoryx produced, I simply didn't know a better way to accomplish the goal. I'm eager to learn a better way!

Happy coding everyone!

![bitmoji](https://render.bitstrips.com/v2/cpanel/07c1858a-7acb-47e4-8f2a-252a1fe9f362-b427cfda-a7f5-497f-a483-1061dc3d44a5-v1.png?transparent=1&palette=1&width=246)
